export const PAKISTANI_BANKS = [
  "AlBaraka Bank (Pakistan) Limited",
  "Allied Bank Limited",
  "Askari Bank Limited",
  "Bank AL Habib Limited",
  "Bank Alfalah Limited",
  "Bank Makramah Limited",
  "BankIslami Pakistan Limited",
  "Citibank N.A.",
  "Deutsche Bank AG",
  "Dubai Islamic Bank Pakistan Limited",
  "Faysal Bank Limited",
  "First Women Bank Limited",
  "Habib Bank Limited (HBL)",
  "Habib Metropolitan Bank Limited",
  "Industrial and Commercial Bank of China Limited",
  "JS Bank Limited",
  "MCB Bank Limited",
  "MCB Islamic Bank Limited",
  "Meezan Bank Limited",
  "National Bank of Pakistan (NBP)",
  "Punjab Provincial Cooperative Bank Limited",
  "Samba Bank Limited",
  "Sindh Bank Limited",
  "SME Bank Limited",
  "Soneri Bank Limited",
  "Standard Chartered Bank (Pakistan) Limited",
  "The Bank of Khyber",
  "The Bank of Punjab",
  "United Bank Limited (UBL)",
  "Zarai Taraqiati Bank Limited (ZTBL)",
  "Telenor Microfinance Bank (Easypaisa)",
  "Mobilink Microfinance Bank (JazzCash)",
] as const;

export const TEAMS = [
  "Sajid Team",
  "Zain Team",
  "Asim Team",
  "Awais Yousaf Team",
  "Kashif Team",
  "Waseel Team",
] as const;
